import csv
import firebase_admin
from firebase_admin import credentials, firestore

# Initialize Firebase Admin SDK
cred = credentials.Certificate("key.json")
firebase_admin.initialize_app(cred)

# Create a Firestore client
db = firestore.client()

# Read and parse the CSV file
with open('products.csv', 'r') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    for row in csv_reader:
        # Convert the appropriate fields to the correct data types
        product_data = {
            'id': int(row['id']),
            'name': row['name'],
            'imageUrl': row['imageUrl'],
            'category': row['category'],
            'type': row['type'],
            'price': float(row['price']),
            'review': float(row['review']),
            'value': int(row['value']),
            'selectedColor': int(row['selectedColor']),
            'selectedSize': int(row['selectedSize']),
            'color': row['color'],
            'season': row['season'], 
        }

        # Add the data to Firestore in the 'products2' collection with an autogenerated document ID
        db.collection('products2').add(product_data)
